server:
  port: 45432
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mhmnz?currentSchema=public
    username: postgres
    password: Fk12345.
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
  task:
    scheduling:
      thread-name-prefix: scheduler-
      pool:
        size: 2
logging:
  level:
    cc.yiueil: debug
    web: debug
yiueil:
  hello:
    suffix: 再见
    prefix: 你好
debug: true