server:
  port: 45432
spring:
  datasource:
    url: jdbc:postgresql://47.109.40.4:65432/mhmnz?currentSchema=public
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
  task:
    scheduling:
      thread-name-prefix: scheduler-
      pool:
        size: 2
logging:
  level:
    cc.yiueil: debug
    web: debug